name: malison_flutter
description: malison for flutter
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  malison: ^0.11.0
  piecemeal: any
  collection: any

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
